import type { Token, TokenSet } from "../model.ts";

/**
 * A generator of one file (code for a platform, or an asset such as an icon). Implementations must
 * be pure and deterministic.
 */
export interface Emitter {
  /** Path of the generated file, relative to the brand project. */
  readonly outputPath: string;
  /** Text, or the bytes of a binary file. */
  emit(set: TokenSet): string | Uint8Array | Promise<string | Uint8Array>;
}

export const GENERATED_NOTICE = "Generated by brand from brand/tokens — DO NOT EDIT.";

/** Groups tokens by their root segment, preserving declaration order. */
export function groupByRoot(tokens: readonly Token[]): Map<string, Token[]> {
  const groups = new Map<string, Token[]>();
  for (const token of tokens) {
    const list = groups.get(token.path.root) ?? [];
    list.push(token);
    groups.set(token.path.root, list);
  }
  return groups;
}

/** Zips light and dark tokens (same order is guaranteed by the loader). */
export function themedPairs(set: TokenSet): { light: Token; dark: Token }[] {
  return set.themes.light.map((light, i) => {
    const dark = set.themes.dark[i];
    if (dark === undefined) throw new Error(`${light.path.dotted} has no dark value`);
    return { light, dark };
  });
}

export function formatNumber(value: number): string {
  return Number.isInteger(value) ? String(value) : String(Number(value.toFixed(4)));
}

/** `#RRGGBB` / `#RRGGBBAA` → `0xAARRGGBB` (used by Swift and Kotlin emitters). */
export function argbLiteral(hex: string): string {
  const rgb = hex.slice(1, 7);
  const alpha = hex.length === 9 ? hex.slice(7, 9) : "FF";
  return `0x${alpha}${rgb}`.toUpperCase().replace("0X", "0x");
}

export function upperFirst(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** Prefix used when a member identifier would otherwise start with a digit (`space.4` → `s4`). */
const NUMERIC_PREFIX: Readonly<Record<string, string>> = { space: "s", elevation: "level" };

/** Swift/Kotlin member identifier for a token, e.g. `text.body-md` → `bodyMd`, `space.4` → `s4`. */
export function memberName(token: Token): string {
  const ident = token.path.toIdentifier();
  if (/^s[0-9]/.test(ident)) {
    return `${NUMERIC_PREFIX[token.path.root] ?? "v"}${ident.slice(1)}`;
  }
  return ident;
}
