import type { Emitter } from "../emitters/emitter.ts";
import type { TokenSet } from "../model.ts";
import sharp from "sharp";
import type { Artwork, BrandExports } from "./exports.ts";

export type Theme = "light" | "dark";

/** The brand colours of a theme (tokens `color.brand.*`) and the app's background (`color.bg.canvas`). */
export class BrandColors {
  readonly ink: string;
  readonly paper: string;
  readonly accent: string;
  readonly canvas: string;

  private constructor(ink: string, paper: string, accent: string, canvas: string) {
    this.ink = ink;
    this.paper = paper;
    this.accent = accent;
    this.canvas = canvas;
  }

  static of(set: TokenSet, theme: Theme): BrandColors {
    const tokens = set.themes[theme];
    const color = (dotted: string): string => {
      const token = tokens.find((t) => t.path.dotted === dotted);
      if (token?.value.kind !== "color") throw new Error(`Missing colour token ${dotted} (${theme})`);
      return token.value.hex;
    };
    return new BrandColors(
      color("color.brand.ink"),
      color("color.brand.paper"),
      color("color.brand.accent"),
      color("color.bg.canvas"),
    );
  }
}

/** Numbers in view boxes and transforms: at most three decimals, no trailing zeros. */
export function formatCoordinate(value: number): string {
  const rounded = Number(value.toFixed(3));
  return Object.is(rounded, -0) ? "0" : String(rounded);
}

/** Embed the entire SVG as one image; definitions and IDs stay scoped to it. */
function image(art: Artwork): string {
  return `<image width="${art.width}" height="${art.height}" href="data:image/svg+xml;base64,${Buffer.from(art.svg).toString("base64")}"/>`;
}

/** Colour the complete image's alpha, without inspecting or rewriting its geometry. */
function silhouette(art: Artwork, fill: string): string {
  return `<defs><filter id="ink" x="0" y="0" width="100%" height="100%" color-interpolation-filters="sRGB"><feFlood flood-color="${fill}"/><feComposite in2="SourceAlpha" operator="in"/></filter></defs><g filter="url(#ink)">${image(art)}</g>`;
}

function escapeXml(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function svg(art: Artwork, body: string, viewBox = `0 0 ${art.width} ${art.height}`): string {
  const label = escapeXml(art.label);
  return `<!-- Generated by brand from ${art.source} — DO NOT EDIT. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" role="img" aria-label="${label}"><title>${label}</title>${body}</svg>
`;
}

/** Copy the authored SVG, or wrap the complete image for a monochrome appearance. */
export class ArtworkSvg implements Emitter {
  readonly outputPath: string;
  private readonly art: Artwork;
  private readonly paint: Theme | "currentColor";

  constructor(outputPath: string, art: Artwork, paint: Theme | "currentColor") {
    this.outputPath = outputPath;
    this.art = art;
    this.paint = paint;
  }

  emit(set: TokenSet): string {
    if (this.paint === "light") return this.art.svg;
    const fill = this.paint === "currentColor" ? "currentColor" : BrandColors.of(set, this.paint).ink;
    return svg(this.art, silhouette(this.art, fill));
  }
}

export class FaviconSvg implements Emitter {
  readonly outputPath: string;
  private readonly mark: Artwork;

  constructor(outputPath: string, mark: Artwork) {
    this.outputPath = outputPath;
    this.mark = mark;
  }

  emit(set: TokenSet): string {
    const side = Math.max(this.mark.width, this.mark.height);
    const box = [(this.mark.width - side) / 2, (this.mark.height - side) / 2, side, side]
      .map(formatCoordinate)
      .join(" ");
    const style = `<style>feFlood{flood-color:${BrandColors.of(set, "light").ink}}@media (prefers-color-scheme:dark){feFlood{flood-color:${BrandColors.of(set, "dark").ink}}}</style>`;
    return svg(this.mark, style + silhouette(this.mark, "currentColor"), box);
  }
}

export class AppIconSvg implements Emitter {
  readonly outputPath: string;
  private readonly icon: Artwork;

  constructor(outputPath: string, icon: Artwork) {
    this.outputPath = outputPath;
    this.icon = icon;
  }

  emit(set: TokenSet): string {
    const c = BrandColors.of(set, "light");
    return svg(
      this.icon,
      `<rect width="${this.icon.width}" height="${this.icon.height}" fill="${c.paper}"/>${image(this.icon)}`,
    );
  }
}

/** Render the complete SVG at the requested size, then colour its alpha and add padding. */
export async function renderArtwork(
  art: Artwork,
  width: number,
  height: number,
  fill: string,
  padding = 0,
): Promise<Buffer> {
  const contentWidth = width - padding * 2;
  const contentHeight = height - padding * 2;
  const density = Math.max(72, Math.ceil(72 * Math.max(contentWidth / art.width, contentHeight / art.height)));
  const mask = await sharp(Buffer.from(art.svg), { density })
    .resize(contentWidth, contentHeight, { fit: "contain", background: "#00000000" })
    .png()
    .toBuffer();
  const coloured = await sharp({
    create: { width: contentWidth, height: contentHeight, channels: 4, background: fill },
  })
    .composite([{ input: mask, blend: "dest-in" }])
    .png()
    .toBuffer();
  return sharp(coloured)
    .extend({ top: padding, bottom: padding, left: padding, right: padding, background: "#00000000" })
    .png()
    .toBuffer();
}

/** What a PNG is painted with: a theme's ink or paper, white, or a literal `#RRGGBB(AA)`. */
export type Paint = Theme | "white" | `#${string}`;

function paintColor(set: TokenSet, paint: Paint, role: "ink" | "paper"): string {
  if (paint === "white") return "#FFFFFF";
  if (paint.startsWith("#")) return paint;
  const colors = BrandColors.of(set, paint as Theme);
  return role === "ink" ? colors.ink : colors.paper;
}

export interface PngOptions {
  readonly width: number;
  readonly height: number;
  /** The artwork's colour: a theme's ink, white, or a literal colour. */
  readonly paint: Paint;
  /** Transparent margin around the artwork, in pixels. */
  readonly padding?: number;
  /** Fills the canvas behind the artwork: a theme's paper, white, or a literal colour. Transparent when absent. */
  readonly background?: Paint;
}

/** The complete artwork rendered as a PNG: app launcher layers, avatars, emojis. */
export class ArtworkPng implements Emitter {
  readonly outputPath: string;
  private readonly art: Artwork;
  private readonly options: PngOptions;

  constructor(outputPath: string, art: Artwork, options: PngOptions) {
    this.outputPath = outputPath;
    this.art = art;
    this.options = options;
  }

  async emit(set: TokenSet): Promise<Uint8Array> {
    const { width, height, paint, padding = 0, background } = this.options;
    const art = await renderArtwork(this.art, width, height, paintColor(set, paint, "ink"), padding);
    if (background === undefined) return art;
    return sharp({ create: { width, height, channels: 4, background: paintColor(set, background, "paper") } })
      .composite([{ input: art }])
      .png()
      .toBuffer();
  }
}

function androidPng(path: string, art: Artwork, width: number, height: number, paint: Paint, padding = 0): Emitter {
  return new ArtworkPng(path, art, { width, height, paint, padding });
}

/** Android accepts bitmap drawables, including adaptive-icon and notification layers. */
export function androidArtwork(res: string, brand: BrandExports): Emitter[] {
  const densities = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };
  return Object.entries(densities).flatMap(([density, scale]) => {
    const drawable = `${res}/drawable-${density}`;
    const side = Math.round(108 * scale);
    const padding = Math.round(18 * scale);
    return [
      androidPng(`${drawable}/ic_launcher_foreground.png`, brand.appIcon, side, side, "light", padding),
      androidPng(`${drawable}/ic_launcher_monochrome.png`, brand.appIcon, side, side, "white", padding),
      androidPng(`${drawable}/ic_splash.png`, brand.appIcon, side, side, "light", padding),
      androidPng(`${res}/drawable-night-${density}/ic_splash.png`, brand.appIcon, side, side, "dark", padding),
      androidPng(
        `${drawable}/ic_notification.png`,
        brand.mark,
        Math.round(24 * scale),
        Math.round(24 * scale),
        "white",
        Math.round(2 * scale),
      ),
      androidPng(
        `${drawable}/ic_logo.png`,
        brand.logo,
        Math.round(((32 * brand.logo.width) / brand.logo.height) * scale),
        Math.round(32 * scale),
        "light",
      ),
    ];
  });
}

/**
 * Android's colour resources for what shows before Compose draws: the window's background and the
 * launcher icon's paper (which stays light — launcher icons don't follow the theme).
 */
export class AndroidColors implements Emitter {
  readonly outputPath: string;
  private readonly theme: Theme;

  constructor(outputPath: string, theme: Theme) {
    this.outputPath = outputPath;
    this.theme = theme;
  }

  emit(set: TokenSet): string {
    const c = BrandColors.of(set, this.theme);
    const paper = BrandColors.of(set, "light").paper;
    const icon = this.theme === "light" ? `\n    <color name="icon_paper">${paper}</color>` : "";
    return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by brand from brand/tokens — DO NOT EDIT. -->
<resources>
    <color name="canvas">${c.canvas}</color>${icon}
</resources>
`;
  }
}
